general:
  dir_input: ""     # <directory where offical iso are>
  dir_isocustom: "" # <directory to put custom iso>
  dir_build: ""     # <temp directory where we build iso>

download :
  debian-9.6.0-strech-amd64-netinst.iso:
    label: Debian 9.6.0 Strech amd64 Netinst
    url_iso: https://cdimage.debian.org/debian-cd/9.6.0/amd64/iso-cd/debian-9.6.0-amd64-netinst.iso
    hash:
      type: sha1
      sum: ed1cf0dea20831fb26661c10ca65340e3a3ea616

  debian-10-buster-amd64-netinst-testing.iso:
    label: Debian 10 Buster testing amd64 Netinstall
    url_iso: https://cdimage.debian.org/cdimage/buster_di_alpha1/amd64/iso-cd/debian-buster-DI-alpha1-amd64-netinst.iso

  ubuntu-16.04.4-LTS-Xenial_Xerus-amd64-desktop-live.iso:
    label :  Ubuntu 16.04.4 LTS Xenial_Xerus amd64 desktop live
    url_iso : https://www.ubuntu.com/download/desktop/thank-you?country=FR&version=16.04.4&architecture=amd64

  ubuntu-16.04.4-LTS-Xenial_Xerus-amd64-server.iso:
    label :  Ubuntu 16.04.4 LTS Xenial_Xerus amd64 server
    url_iso : http://releases.ubuntu.com/16.04.4/ubuntu-16.04.4-server-amd64.iso

  ubuntu-17.10.1-Artful_Aardvark-amd64-server.iso:
    label : Ubuntu 17.10.1 Artful Aardvark amd64 server
    url_iso: https://www.ubuntu.com/download/server/thank-you?country=FR&version=17.10.1&architecture=amd64

  linuxmint-18.2-Sonya-amd64-desktop-cinnamon.iso :
    label : Linux Mint 18.2 amd64 desktop Cinnamon
    url_iso : http://mint-mirror.gwendallebihan.net/isos/stable/18.2/linuxmint-18.2-cinnamon-64bit.iso

  kde-18.3-destop-kde.iso :
    label : Kde 18.3 amd64 destop Kde
    url_iso : http://www.kubuntu-fr.org/telechargement?action=dl

  centos-7-x86-amd64-desktop.iso :
    label : CentOS 7 x86_amd64 desktop
    url_iso : http://miroir.univ-paris13.fr/centos/7/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso

  raspbian-9-stretch-lite.img :
    label : Raspbian stretch Lite
    url_iso : https://downloads.raspberrypi.org/raspbian_lite_latest
    hash:
      type: sha256
      sum: 3271b244734286d99aeba8fa043b6634cad488d211583814a2018fc14fdca313

custom :
  Custom-FullAuto-Debian-9-strech-amd64-netinst-server.iso :
    label : Custom FullAuto Debian 9 Amd64 netinst server
    template : preseed-Debian-9-strech-amd64-srv.cfg.j2
    iso_base : debian-9.6.0-strech-amd64-netinst.iso
    transfom : customDebian9soft

  Custom-FullAuto-Debian-9-strech-amd64-netinst-server-proliant.iso :
    label : Custom FullAuto Debian 9 Amd64 netinst server for proliant jcnaud
    template : preseed-Debian-9-strech-amd64-srv-proliant.cfg.j2
    iso_base : debian-9.6.0-strech-amd64-netinst.iso
    transfom : customDebian9soft

  Custom-FullAuto-Ubuntu-16-LTS-Xenial_Xerus-amd64-desktop.iso :
    label : Custom FullAuto Ubuntu 16 Amd64 Desktop
    template : kickstart-Ubuntu-16-xenial-amd-64-desktop.cfg.j2
    iso_base : ubuntu-16.04.4-LTS-Xenial_Xerus-amd64-server.iso
    transfom : customUbuntu16soft

  Custom-FullAuto-Ubuntu-17-Artful_Aardvark-amd64-desktop.iso :
    label : Custom FullAuto Ubuntu 16 Amd64 Desktop
    template : kickstart-Ubuntu-17-artful-amd-64-desktop.cfg.j2
    iso_base : ubuntu-17.10.1-Artful_Aardvark-amd64-server.iso
    transfom : customUbuntu17soft

virtualbox:
  vms:
    Debian-amd64-standard:      # <unique name>
      #hostname: 'test debian'
      os_type : 'Debian_64'     # <Id> of the liste : VBoxManage list ostypes |egrep '^ID:'|awk '{print $2}'
      file_disk_type : 'vmdk'   # <vdi | vmdk>
      ram : 1024              # <ram size Mo> multiple of x^2 : example 1*1024
      vram : 128              # <video ram size Mo>
      disk_size : 32768       # <disk size Mo> multiple of x^2 : example 8*1024
      interface_name: 'wlan0'      # <interface> to connection with this vms
      interface_type: 'bridged'    # bridged | ...

    Debian-amd64-raid:
      #hostname: 'test debian'
      os_type : 'Debian_64'     # Id fourni dans la liste : VBoxManage list ostypes |egrep '^ID:'|awk '{print $2}'
      file_disk_type : 'wlan0'   # vdi | vmdk
      ram : 1024              # multiple de x^2 : exemple 1*1024
      vram : 128              # mémoire video
      disk_size : [32768,32768]       # multiple de x^2 : exemple 8*1024

      interface_name: 'wlan0'      # Votre interface de connection externe donnée par /sbin/ifconfig
      interface_type: 'bridged'    # bridged | ...
